version: 2

updates:
  # Python (Poetry / pip)
  - package-ecosystem: "pip"
    directory: "/"                 # Location of pyproject.toml / poetry.lock
    schedule:
      interval: "weekly"
    # Optional settings:
    # rebase-strategy: "auto"
    # allow:
    #   - dependency-type: "direct" # "direct" or "all"

  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "HydraDragonFirewall/hydradragonfirewall"
    schedule:
      interval: "weekly"
