[build]
# Use default jobs (auto-detect CPU cores)

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:67108864", "-C", "linker=rust-lld.exe"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:67108864", "-C", "linker=rust-lld.exe"]

[profile.dev]
incremental = true

[profile.release]
lto = "thin"
